In [2]:
import numpy as np
import pandas as pd
from sksurv.datasets import load_whas500
from sksurv.linear_model import CoxPHSurvivalAnalysis
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
LIMIT=10

In [6]:
X, y = load_whas500()

display(X[:5])
display(y[:5])
display(f'Number of features: {len(X.columns)}')
display(f'Number of samples" {X.shape[0]}')

,afb,age,av3,bmi,chf,cvd,diasbp,gender,hr,los,miord,mitype,sho,sysbp
0,1,83.0,0,25.54051,0,1,78.0,0,89.0,5.0,1,0,0,152.0
1,0,49.0,0,24.02398,0,1,60.0,0,84.0,5.0,0,1,0,120.0
2,0,70.0,0,22.14290,0,0,88.0,1,83.0,5.0,0,1,0,147.0
3,0,70.0,0,26.63187,1,1,76.0,0,65.0,10.0,0,1,0,123.0
4,0,70.0,0,24.41255,0,1,85.0,0,63.0,6.0,0,1,0,135.0

array([(False, 2178.), (False, 2172.), (False, 2190.), ( True,  297.),
       (False, 2131.)], dtype=[('fstat', '?'), ('lenfol', '<f8')])

'Number of features: 14'

'Number of samples" 500'

In [9]:
@np.vectorize
def include(event):
    return event[0]

non_censored_X = X[include(y)]
non_censored_y = y[include(y)]

non_censored_X

,afb,age,av3,bmi,chf,cvd,diasbp,gender,hr,los,miord,mitype,sho,sysbp
3,0,70.0,0,26.63187,1,1,76.0,0,65.0,10.0,0,1,0,123.0
5,0,70.0,1,23.24236,0,1,54.0,0,76.0,1.0,0,0,0,83.0
7,0,55.0,0,27.11609,0,1,95.0,0,91.0,4.0,0,1,0,147.0
8,0,88.0,0,27.43554,1,1,100.0,1,63.0,4.0,0,0,0,209.0
11,1,75.0,0,28.69720,1,1,123.0,0,154.0,10.0,0,1,0,193.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,0,93.0,0,23.72658,1,1,60.0,0,110.0,5.0,1,0,0,158.0
493,0,83.0,0,42.38277,1,1,88.0,0,92.0,5.0,1,0,0,160.0
494,0,92.0,0,24.75240,1,1,114.0,1,92.0,3.0,1,0,0,216.0
495,1,76.0,0,27.96454,0,1,88.0,1,68.0,1.0,0,1,0,112.0
499,0,98.0,0,19.48575,0,1,100.0,0,99.0,3.0,0,1,0,160.0

In [10]:
cox_model = CoxPHSurvivalAnalysis()

cox_model.fit(non_censored_X, non_censored_y)

CoxPHSurvivalAnalysis()

In [12]:
cox_model.coef_

array([-2.18736506e-01,  7.25206430e-03, -7.82094419e-01, -3.64531784e-02,
        3.36355089e-01, -6.38655336e-02, -8.81484274e-03, -2.79366310e-01,
        3.26195076e-03, -1.69472313e-02, -9.62556466e-02, -2.14628198e-02,
        1.21333589e+00,  7.60421653e-04])

In [13]:
cox_model.baseline_survival_

StepFunction(x=array([1.000e+00, 2.000e+00, 3.000e+00, 4.000e+00, 5.000e+00, 6.000e+00,
       7.000e+00, 1.000e+01, 1.100e+01, 1.400e+01, 1.600e+01, 1.700e+01,
       1.800e+01, 1.900e+01, 2.000e+01, 2.200e+01, 2.600e+01, 3.100e+01,
       3.200e+01, 3.300e+01, 3.400e+01, 3.700e+01, 4.200e+01, 4.600e+01,
       4.900e+01, 5.200e+01, 5.300e+01, 5.500e+01, 5.700e+01, 6.000e+01,
       6.100e+01, 6.200e+01, 6.400e+01, 6.900e+01, 7.600e+01, 8.100e+01,
       8.300e+01, 8.800e+01, 9.100e+01, 9.300e+01, 9.500e+01, 9.700e+01,
       1.000e+02, 1.010e+02, 1.080e+02, 1.090e+02, 1.130e+02, 1.160e+02,
       1.170e+02, 1.180e+02, 1.290e+02, 1.320e+02, 1.340e+02, 1.350e+02,
       1.370e+02, 1.400e+02, 1.430e+02, 1.450e+02, 1.460e+02, 1.510e+02,
       1.660e+02, 1.690e+02, 1.870e+02, 1.920e+02, 1.970e+02, 2.000e+02,
       2.260e+02, 2.330e+02, 2.350e+02, 2.590e+02, 2.690e+02, 2.740e+02,
       2.870e+02, 2.890e+02, 2.950e+02, 2.970e+02, 3.120e+02, 3.130e+02,
       3.210e+02, 3.280e+02, 3.430e+02, 3.450e+02, 3.540e+02, 3.580e+02,
       3.590e+02, 3.630e+02, 3.820e+02, 3.850e+02, 3.920e+02, 3.970e+02,
       4.050e+02, 4.060e+02, 4.190e+02, 4.220e+02, 4.420e+02, 4.460e+02,
       4.650e+02, 4.670e+02, 4.730e+02, 4.790e+02, 4.970e+02, 5.300e+02,
       5.350e+02, 5.370e+02, 5.420e+02, 5.520e+02, 5.590e+02, 5.620e+02,
       6.120e+02, 6.140e+02, 6.320e+02, 6.440e+02, 6.460e+02, 6.490e+02,
       6.540e+02, 6.700e+02, 6.730e+02, 7.040e+02, 7.140e+02, 7.180e+02,
       8.490e+02, 8.650e+02, 9.030e+02, 9.050e+02, 9.200e+02, 9.360e+02,
       9.530e+02, 1.048e+03, 1.054e+03, 1.065e+03, 1.096e+03, 1.136e+03,
       1.152e+03, 1.159e+03, 1.165e+03, 1.174e+03, 1.200e+03, 1.217e+03,
       1.232e+03, 1.233e+03, 1.279e+03, 1.317e+03, 1.359e+03, 1.377e+03,
       1.496e+03, 1.506e+03, 1.527e+03, 1.536e+03, 1.548e+03, 1.553e+03,
       1.576e+03, 1.577e+03, 1.579e+03, 1.624e+03, 1.627e+03, 1.671e+03,
       1.926e+03, 1.954e+03, 2.160e+03, 2.350e+03, 2.353e+03, 2.358e+03]), y=array([9.36229580e-01, 8.74109234e-01, 8.50576993e-01, 8.34622632e-01,
       8.18580916e-01, 7.78633622e-01, 7.31645307e-01, 7.07724283e-01,
       6.76004157e-01, 6.60436349e-01, 6.52599109e-01, 6.37122141e-01,
       6.14292969e-01, 5.91951358e-01, 5.77206920e-01, 5.62680516e-01,
       5.55350429e-01, 5.48056569e-01, 5.33680950e-01, 5.12476895e-01,
       5.05457700e-01, 4.98469041e-01, 4.91464845e-01, 4.84529197e-01,
       4.77658903e-01, 4.70830079e-01, 4.64012471e-01, 4.57244653e-01,
       4.43890980e-01, 4.37270162e-01, 4.30696213e-01, 4.24200720e-01,
       4.11419465e-01, 3.98872096e-01, 3.92665902e-01, 3.86518803e-01,
       3.80437401e-01, 3.74406403e-01, 3.68415124e-01, 3.62479060e-01,
       3.56597506e-01, 3.50779769e-01, 3.45022452e-01, 3.39299811e-01,
       3.33623244e-01, 3.27964496e-01, 3.22311220e-01, 3.16721946e-01,
       3.11219691e-01, 3.05774122e-01, 3.00352690e-01, 2.94974701e-01,
       2.89675341e-01, 2.84424512e-01, 2.79215597e-01, 2.69047511e-01,
       2.63972397e-01, 2.58913459e-01, 2.53933085e-01, 2.49012450e-01,
       2.44140638e-01, 2.34523840e-01, 2.24968541e-01, 2.20244258e-01,
       2.15582158e-01, 2.10975892e-01, 2.06400376e-01, 2.01874817e-01,
       1.97420027e-01, 1.88713738e-01, 1.84415750e-01, 1.80174836e-01,
       1.76006366e-01, 1.71876608e-01, 1.67803159e-01, 1.59776801e-01,
       1.55829163e-01, 1.51887648e-01, 1.47970052e-01, 1.44106273e-01,
       1.40312897e-01, 1.36542610e-01, 1.32801357e-01, 1.29099838e-01,
       1.21938537e-01, 1.18401882e-01, 1.14920387e-01, 1.11476533e-01,
       1.08079896e-01, 1.04762921e-01, 1.01490999e-01, 9.82947777e-02,
       9.51543531e-02, 9.20065451e-02, 8.89220451e-02, 8.59012037e-02,
       8.28296073e-02, 7.98267115e-02, 7.68994260e-02, 7.40249972e-02,
       7.12463623e-02, 6.84982730e-02, 6.58170661e-02, 6.31907711e-02,
       6.06243998e-02, 5.80986213e-02, 5.56107803e-02, 5.31810693e-02,
       5.08019920e-02, 4.84939104e-02, 4.62586579e-02, 4.40868343e-02,
       4.19700240e-02, 3.98706278e-02, 3.78472597e-02, 3.58720518e-02,
       3.39680466e-02, 3.21438249e-02, 3.03828528e-02, 2.86744982e-02,
       2.70038047e-02, 2.53846786e-02, 2.38288561e-02, 2.23314024e-02,
       2.08846715e-02, 1.94970395e-02, 1.81618892e-02, 1.68793129e-02,
       1.56626186e-02, 1.44994151e-02, 1.33966109e-02, 1.23551159e-02,
       1.13544226e-02, 1.03672499e-02, 9.42994746e-03, 8.53100496e-03,
       7.67943101e-03, 6.89627047e-03, 6.17022303e-03, 5.50331799e-03,
       4.86791849e-03, 4.28508639e-03, 3.75672408e-03, 2.84255635e-03,
       2.43341391e-03, 2.06684494e-03, 1.73469495e-03, 1.44137933e-03,
       1.17657630e-03, 9.39634844e-04, 7.14403573e-04, 5.27768364e-04,
       3.84952154e-04, 2.66193924e-04, 1.74070683e-04, 1.08445668e-04,
       6.16723510e-05, 3.07079668e-05, 1.41257209e-05, 4.34840337e-06,
       5.24617553e-07, 4.62786239e-09]), a=1.0, b=0.0)